name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        env:
          COMPOSER_AUDIT_BLOCK_INSECURE: 'false'
        run: composer install --no-progress --no-interaction

      - name: Lint
        run: composer lint:check

      - name: Test
        run: composer test
